ALTER TABLE `order`
  DROP FOREIGN KEY `Order_userId_fkey`;

ALTER TABLE `order`
  MODIFY COLUMN `userId` INTEGER NULL;

ALTER TABLE `order`
  ADD CONSTRAINT `Order_userId_fkey`
  FOREIGN KEY (`userId`) REFERENCES `user`(`id`)
  ON DELETE SET NULL ON UPDATE CASCADE;
